[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "rm -rf .angular",
  "echo '=== DEBUG BUILD ==='",
  "node -v",
  "npm -v",
  "npx ng version",
  "NODE_OPTIONS=--max-old-space-size=2048 npx ng build --configuration development"
]

[start]
cmd = "npx serve -s dist"
