[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "rm -rf .angular",
  "NODE_OPTIONS=--max-old-space-size=2048 npx ng build --configuration development"
]

[start]
cmd = "npx serve -s dist"
